apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: '-'
build:
  artifacts:
  - image: rinat82/arch-py-hw
    context: hw-app
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - ingress.yaml
    - service.yaml
